[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/apache2.log
stderr_logfile=/var/log/supervisor/apache2_err.log

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd_err.log

[program:named]
command=/usr/sbin/named -g -c /etc/bind/named.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/named.log
stderr_logfile=/var/log/supervisor/named_err.log

[program:vsftpd]
command=/usr/sbin/vsftpd /etc/vsftpd.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/vsftpd.log
stderr_logfile=/var/log/supervisor/vsftpd_err.log

[program:mariadb]
command=/usr/bin/mysqld_safe
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/mariadb.log
stderr_logfile=/var/log/supervisor/mariadb_err.log
# MariaDB doit démarrer avant Apache/DVWA
priority=1

[program:init-db]
command=/docker-entrypoint-initdb.d/init-db.sh
autostart=true
autorestart=false
startsecs=0
priority=2
stdout_logfile=/var/log/supervisor/init-db.log
stderr_logfile=/var/log/supervisor/init-db_err.log
